---
title: "WORLE rainfall simulation bacterial diversity"
output:
  html_document:
    df_print: paged
    fig_width: 8.5
    fig_height: 11
    fig_caption: true
    toc: true
    toc_float: true
    number_sections: false
    code_folding: hide
---

```{r, echo=F}
library(phyloseq)
library(phylosmith)
library(tidyverse)
library(viridis)
```

```{r, message = F, warning = F}
phy <- readRDS("./data/RDS/worle_with_meta.RDS")
```

```{r}
data <- data.frame(sample_data(phy)) %>%
  filter(matrix == "soil") %>%
  mutate(Vegetation = case_when(in_plot_location %in% c("s1", "s2", "s3", "s4") ~ "Crop",
                                in_plot_location %in% c("s6", "s7", "s8", "s9") ~ "Prairie",
                                TRUE ~ "Border"))

all_data <- data.frame(sample_data(phy)) %>%
  full_join(data)

all_data <- all_data %>%
  mutate(day = replace(day, day == 't2', "t02"))

sample_names(phy)

rownames(all_data) <- all_data$id

sample_data(phy) <- all_data
```

```{r}
colnames(phy@sam_data)
unique(phy@sam_data$matrix)
unique(phy@sam_data$day)
unique(phy@sam_data$depth)
unique(phy@sam_data$treatment)


base_all_measures <- subset_samples(phy, matrix == "soil" & day == "b" & depth == "d1") 

min(taxa_sums(base_all_measures))
 
plot_richness(base_all_measures, x = "Vegetation", color = "treatment")
```
```{r}
t0_all_measures <- subset_samples(phy, matrix == "soil" & day == "t0" & depth == "d1") 

plot_richness(t0_all_measures, x = "Vegetation", color = "treatment")
```
```{r}
t2_all_measures <- subset_samples(phy, matrix == "soil" & day == "t02" & depth == "d1") 

plot_richness(t2_all_measures, x = "Vegetation", color = "treatment")
```
```{r}
t14_all_measures <- subset_samples(phy, matrix == "soil" & day == "t14" & depth == "d1") 

plot_richness(t14_all_measures, x = "Vegetation", color = "treatment")
```
```{r}
t42_all_measures <- subset_samples(phy, matrix == "soil" & day == "t42" & depth == "d1") 

plot_richness(t42_all_measures, x = "Vegetation", color = "treatment")
```
```{r}
all.days.prairie.appended.d1 <- subset_samples(phy, matrix == "soil" & depth == "d1" & treatment %in% c("no_manure_strip", "manured_strip"))
all.days.prairie.appended.d2 <- subset_samples(phy, matrix == "soil" & depth == "d2" & treatment %in% c("no_manure_strip", "manured_strip"))

plot_richness(all.days.prairie.appended.d1, x = "day", color = "treatment", measures = c("Observed", "Shannon"))
plot_richness(all.days.prairie.appended.d2, x = "day", color = "treatment", measures = c("Observed", "Shannon"))
```

