---
title: "Analysis of WORLE 2017 soils and water 16s rRNA"
author: "Jared"
date: "6/20/2019"
output:
  html_document:
    df_print: paged
    fig_width: 8.5
    fig_height: 11
    fig_caption: true
    toc: true
    toc_float: true
    number_sections: false
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### First we read in the data, a R data structure of the phyloseq object       
```{r, echo = F}
library(phyloseq)
library(tidyverse)
library(gplots)
library(phylosmith)
```
```{r}
# source functions
source("code/functions.R")
```

```{r}
phy <- readRDS("./data/RDS/worle_with_meta.RDS")
colnames(sample_data(phy))
unique(phy@sam_data$day)
data <- data.frame(sample_data(phy)) %>%
  filter(matrix == "soil") %>%
  mutate(Vegetation = case_when(in_plot_location %in% c("s1", "s2", "s3", "s4") ~ "Crop",
                                in_plot_location %in% c("s6", "s7", "s8", "s9") ~ "Prairie",
                                TRUE ~ "Border"))

all_data <- data.frame(sample_data(phy)) %>%
  full_join(data)

all_data <- all_data %>%
  mutate(day = replace(day, day == 't2', "t02"))

sample_names(phy)

rownames(all_data) <- all_data$id

sample_data(phy) <- all_data
```
```{r}
hist(sample_sums(phy), breaks = 100)
```

### Get a list of ASVs from manure and soil before manure was applied
```{r}
manure_otus <- subset_samples(phy, matrix == "manure") %>%
  filter_taxa(function(x) sum(x) >= 1, T) %>%
  otu_table() %>%
  rownames()

cc <- subset_samples(phy, treatment == "no_manure_strip" | day == "b") %>%
  filter_taxa(function(x) sum(x) >= 1, T) %>%
  otu_table() %>%
  rownames()

vvv_diag <- venn(list("Manure_ASVs" = manure_otus, "Soil_ASVs" = cc))
manure_persitors <- attr(vvv_diag, "intersections")$Manure_ASVs 
```

### Plot relative abundance of only manure associated ASVs   
```{r}
# Check reads, I was under the impression that all samples had at least 10k
phy.OTU <- OTU_to_column(phy)
manure.phy <- subset_samples(phy.OTU, matrix == "soil") %>%
  filter_taxa(function(x) sum(x) >= 1, T) %>% 
  transform_sample_counts(function(x) x / sum(x))

persistors.phy <- prune_taxa(manure_persitors, manure.phy) 
sample_data(persistors.phy)
```

### Trying to get a good plot of the abundance of manure associated ASVs
```{r}
plot_bar(persistors.phy, x = "in_plot_location", y = "Abundance") +
  facet_grid(day~treatment)
```

