---
title: "Analysis of WORLE 2017 soils and water 16s rRNA"
author: "Jared"
date: "6/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### First we read in the data, a R data structure of the phyloseq object       
```{r, echo = F}
library(phyloseq)
library(tidyverse)
library(gplots)
library(phylosmith)
```
```{r}
phy <- readRDS("../../data/RDS/worle_with_meta.RDS")
colnames(sample_data(phy))
unique(phy@sam_data$day)
```

### Get a list of ASVs from manure and soil before manure was applied
```{r}
manure_otus <- subset_samples(phy, matrix == "manure") %>%
  filter_taxa(function(x) sum(x) >= 1, T) %>%
  otu_table() %>%
  rownames()

soil_otus <- subset_samples(phy, matrix == "soil" & day == "b") %>%
  filter_taxa(function(x) sum(x) >= 1, T) %>%
  otu_table() %>%
  rownames()
```

### Find ASVs from manure that are not present in any soil baseline sample
```{r}
v_diag <- venn(list("Manure" = manure_otus, "Soil" = soil_otus))

just_manure_ASVs <- attr(v_diag, "intersections")$Manure
```

### Plot relative abundance of only manure associated ASVs   
```{r}
my_subset <- subset(otu_table(phy), rownames(otu_table(phy)) %in% just_manure_ASVs)
manure_ASVs_physeq <- merge_phyloseq(my_subset, tax_table(phy), sample_data(phy)) %>%
  filter_taxa(function(x) sum(x) >= 1, T) 
```

```{r}
taxa_abundance_bars_ggplot(manure_ASVs_physeq, classification = "Phylum", treatment = c("treatment"), subset = c("manured_control", "no_manure_strip", "manured_strip"), transformation = "mean") 
```

